# Generated by Django 3.1.7 on 2021-03-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('details', models.TextField()),
                ('done', models.BooleanField(default=False)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_completion', models.DateField()),
                ('deadline_date', models.DateField()),
            ],
        ),
    ]
