# Generated by Django 3.1.7 on 2021-03-03 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_auto_20210303_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='date_completion',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='done',
        ),
    ]
