# Generated by Django 3.1.7 on 2021-03-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0002_auto_20210307_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.URLField(max_length=700, null=True),
        ),
    ]
