# Generated by Django 3.1.7 on 2021-03-09 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0003_film_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='image',
            new_name='image_url',
        ),
    ]
