# Generated by Django 3.1.7 on 2021-03-09 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('film_app', '0005_likedfilm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedfilm',
            name='user',
        ),
        migrations.AddField(
            model_name='likedfilm',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
