# Generated by Django 3.1.7 on 2021-03-09 14:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('film_app', '0006_auto_20210309_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedfilm',
            name='user',
            field=models.ManyToManyField(related_name='liked_film', to=settings.AUTH_USER_MODEL),
        ),
    ]
