# Generated by Django 3.1.7 on 2021-03-09 15:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('film_app', '0007_auto_20210309_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='liked_film',
            field=models.ManyToManyField(related_name='liked_film', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LikedFilm',
        ),
    ]
